// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	service "github.com/aeramu/menfess-server/internal/auth/service"
	mock "github.com/stretchr/testify/mock"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: email, password, pushToken
func (_m *UserClient) Create(email string, password string, pushToken string) (*service.User, error) {
	ret := _m.Called(email, password, pushToken)

	var r0 *service.User
	if rf, ok := ret.Get(0).(func(string, string, string) *service.User); ok {
		r0 = rf(email, password, pushToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(email, password, pushToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: email
func (_m *UserClient) GetByEmail(email string) (*service.User, error) {
	ret := _m.Called(email)

	var r0 *service.User
	if rf, ok := ret.Get(0).(func(string) *service.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
