// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPushServiceClient is an autogenerated mock type for the PushServiceClient type
type MockPushServiceClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, pushToken, title, body, data
func (_m *MockPushServiceClient) Send(ctx context.Context, pushToken map[string]bool, title string, body string, data string) error {
	ret := _m.Called(ctx, pushToken, title, body, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]bool, string, string, string) error); ok {
		r0 = rf(ctx, pushToken, title, body, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
