// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationClient is an autogenerated mock type for the NotificationClient type
type NotificationClient struct {
	mock.Mock
}

// AddPushToken provides a mock function with given fields: id, pushToken
func (_m *NotificationClient) AddPushToken(id string, pushToken string) error {
	ret := _m.Called(id, pushToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, pushToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemovePushToken provides a mock function with given fields: id, pushToken
func (_m *NotificationClient) RemovePushToken(id string, pushToken string) error {
	ret := _m.Called(id, pushToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, pushToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
